# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldmqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oldmqtt
  template:
    metadata:
      labels:
        app: oldmqtt
    spec:
      containers:
        - name: oldmqtt
          image: ghcr.io/lukacvijic/old-mqtt:latest # check if image name is correct
          # remove this when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oldmqtt
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: oldmqtt