# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendermqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendermqtt
  template:
    metadata:
      labels:
        app: sendermqtt
    spec:
      containers:
        - name: sendermqtt
          image: ghcr.io/lukacvijic/sender-mqtt:latest # check if image name is correct
          # remove this when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sendermqtt
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sendermqtt