# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconsumer
  template:
    metadata:
      labels:
        app: kafkaconsumer
    spec:
      containers:
        - name: kafkaconsumer
          image: ghcr.io/lukacvijic/kafka-consumer:latest # check if image name is correct
          # remove this when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaconsumer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kafkaconsumer