name: Docs

on:
  push:
    branches:
      - 'main'
    paths:
      - asciidocs/**
      - project/**
      - .github/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs
      PROJECTPATH: project
      SLIDES: true
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v4

      - name: Convert AsciiDocs to HTML
        run: |
          sudo ${{ env.INPUTPATH }}/scripts/docker-convert.sh ${{ env.INPUTPATH }} ${{ env.SLIDES }}
          tree ${{ env.INPUTPATH }}

      - name: Include Project Folder
        run: |
          # Copy the project folder into the asciidocs folder
          cp -r ${{ env.PROJECTPATH }} ${{ env.INPUTPATH }}/docs/project
          tree ${{ env.INPUTPATH }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: ${{ env.BRANCH }}
          folder: ${{ env.INPUTPATH }}

