name: Docs

on:
  push:
    branches:
      - 'main'
    paths:
      - asciidocs/**
      - project/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs
      PROJECTPATH: project
      SLIDES: true
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Deployment Folder
        run: |
          # Create a deployment directory
          mkdir deploy
          
          # Move asciidocs content to the root of the deploy directory
          cp -r ${{ env.INPUTPATH }}/* deploy/
          
          # Copy the project folder into the deploy directory as a subfolder
          cp -r ${{ env.PROJECTPATH }} deploy/project

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.BRANCH }}
          folder: deploy
